### ISSUE TITLE
Anchors for AR

### ISSUE THREAD

**Issue by vedhant** [stalgiag/p5.xr#10] opened 2019-03-30 02:52 UTC
As a part of my GSoC project, I would like to implement **Interface for setting and releasing AR anchors**.
Is anchor implemented in the webxr api or will it be added in future? If it is not, then hit test will have to be used to implement anchor in p5 xr.

ARCore uses anchor on top of trackables and session. Maybe I can do something similar where I can anchor objects on a trackable (giving sticky position on the surface tracked) or an object can be anchored to the session (fixed pose in the world space). Is trackables in any form implemented in p5.xr?

I would like to discuss more about this feature since it is a core part of any AR application.

Also, is this repo the complete source code of p5.xr?

**Comment by stalgiag** [comment] 2019-03-30 16:20
Hi @vedhant I agree that anchors are essential for satisfying AR experiences. There are quite a few large hurdles here to be considered. 

- Currently there is heavy WebXR development especially with regards to the AR. While it seems likely that this will stabilize in time for a summer project, there are no guarantees.
- An anchor is essentially just a hit test plus a way to make a model's transform stay persistent. There is a small amount of difficulty in the latter as far as p5 is concerned because most of the individual geometry objects don't retain a transform (position and rotation). This could potentially be solved by deciding how the user interacts with the ideas of hit tests. Perhaps there is a function called something like ::
```
function mousePressed() {
  anchorModel(sphere(100));
}
```
that has to happen inside of a gesture, then it adds a sphere that is drawn in the draw loop that has special flags to apply the matrix that is result of the hit test before drawing. Not sure! This is all just to say that in order for something like anchors to work there will need to be something that modifies the expected behavior of p5 geometry a bit because the logic of how p5 is working internally doesn't suit the persistence that is central to AR anchors. 
- This is related to #6. The XRRay interface can be used to do these hit tests against flat planes in the real world if the phones have ARKit or ARCore. Can this combined with the added tracking of persistent position be used to later de-anchor an object? Essentially, you will need to be able to raycast to objects in order to interact with them once they are placed so this is all related.
- What is the fallback behavior? The VR behavior can be patched into many browsers with the polyfill but it is difficult to know if `requestHitTest()` will be available outside of preview browsers like Chrome Canary/Dev in the immediate future.

This repo isn't the complete src but it is the stable portion. I will slowly migrate work over from a private repo. All of the AR work has been removed because Chrome 73 breaks the previous WebXR API without introducing the changes proposed by the new spec.

**Comment by vedhant** [comment] 2019-03-30 17:12
I'm new to AR/VR and so I'm not sure what are the mathematics of anchors are. From what I can get is that for anchors, each object for a particular anchor will each have a fixed transformation matrix with respect to the anchor. A model matrix with respect to the anchor.
Here,  ```There is a small amount of difficulty in the latter as far as p5 is concerned because most of the individual geometry objects don't retain a transform (position and rotation)``` I'm not able to understand the retaining of transform part.

Also, as mentioned [here](https://codelabs.developers.google.com/codelabs/ar-with-webxr/#1) WebXR API should work for Chrome 70-72

**Comment by stalgiag** [comment] 2019-08-23 14:23
Closing this as anchors will be implemented as per Processing-Android API and this discussion is not longer applicable

**Closed by stalgiag** 2019-08-23 14:23 UTC
